# pubspec.yaml
name: shopease
description: ShopEase - Flutter eCommerce App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_stripe: ^11.5.0
  provider: ^6.1.2
  shared_preferences: ^2.5.5
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  webview_flutter: ^4.13.1
  url_launcher: ^6.3.2
  image_picker: ^1.2.2
  speech_to_text: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/products/
    - assets/icons/