// lib/models/product_model.dart

class Product {
  final String id;
  final String name;
  final String category;
  final double price;
  final double originalPrice;
  final double discount;
  final double rating;
  final int reviewCount;
  final String imageUrl;
  final String description;
  final bool isFeatured;
  final bool isPopular;
  final bool isNewArrival;
  final bool isBestSeller;

  Product({
    required this.id,
    required this.name,
    required this.category,
    required this.price,
    required this.originalPrice,
    required this.discount,
    required this.rating,
    required this.reviewCount,
    required this.imageUrl,
    required this.description,
    this.isFeatured = false,
    this.isPopular = false,
    this.isNewArrival = false,
    this.isBestSeller = false,
  });

  double get discountPercent =>
      originalPrice > 0 ? ((originalPrice - price) / originalPrice * 100) : 0.0;
}

class SampleData {
  static List<Product> get products => [
        // â”€â”€ Sarees â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        Product(
          id: 'p001',
          name: 'Silk Saree ',
          category: 'Sarees',
          price: 1299,
          originalPrice: 2999,
          discount: 57,
          rating: 4.3,
          reviewCount: 1240,
          imageUrl: 'assets/images/products/silk_saree.png',
          description: 'Beautiful silk saree with matching blouse piece. Perfect for weddings and festivals.',
          isFeatured: true,
          isBestSeller: true,
        ),
        Product(
          id: 'p002',
          name: 'Banarasi Silk Saree',
          category: 'Sarees',
          price: 1899,
          originalPrice: 3999,
          discount: 52,
          rating: 4.5,
          reviewCount: 876,
          imageUrl: 'assets/images/products/banarasi_saree.png',
          description: 'Authentic Banarasi silk with golden zari work. A timeless classic.',
          isPopular: true,
        ),
        Product(
          id: 'p003',
          name: 'Chiffon Floral Saree',
          category: 'Sarees',
          price: 599,
          originalPrice: 1299,
          discount: 54,
          rating: 4.1,
          reviewCount: 543,
          imageUrl: 'assets/images/products/chiffon_floral_saree.png',
          description: 'Light and flowy chiffon saree with floral print. Ideal for casual wear.',
          isNewArrival: true,
        ),
        Product(
          id: 'p004',
          name: 'Cotton Handloom Saree',
          category: 'Sarees',
          price: 799,
          originalPrice: 1599,
          discount: 50,
          rating: 4.2,
          reviewCount: 320,
          imageUrl: 'assets/images/products/cotton_handloom_saree.png',
          description: 'Handwoven cotton saree from traditional artisans.',
          isBestSeller: true,
        ),
        Product(
          id: 'p004b',
          name: 'Georgette Party Saree',
          category: 'Sarees',
          price: 999,
          originalPrice: 2199,
          discount: 55,
          rating: 4.4,
          reviewCount: 412,
          imageUrl: 'assets/images/products/georgette_party_saree.png',
          description: 'Gorgeous georgette saree perfect for parties and events.',
          isPopular: true,
          isFeatured: true,
        ),

        // â”€â”€ Women Fashion â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        Product(
          id: 'p005',
          name: 'Trendy Floral Kurti',
          category: 'Women Fashion',
          price: 349,
          originalPrice: 799,
          discount: 56,
          rating: 4.0,
          reviewCount: 987,
          imageUrl: 'assets/images/products/trendy_floral_kurti.png',
          description: 'Stylish floral printed kurti, perfect for daily wear.',
          isFeatured: true,
          isPopular: true,
        ),
        Product(
          id: 'p006',
          name: 'Women Plazo Set',
          category: 'Women Fashion',
          price: 499,
          originalPrice: 999,
          discount: 50,
          rating: 4.2,
          reviewCount: 654,
          imageUrl: 'assets/images/products/women_plazo_set.png',
          description: 'Comfortable plazo set for everyday wear.',
          isNewArrival: true,
        ),
        Product(
          id: 'p007',
          name: 'Embroidered Anarkali Suit',
          category: 'Women Fashion',
          price: 899,
          originalPrice: 1999,
          discount: 55,
          rating: 4.4,
          reviewCount: 432,
          imageUrl: 'assets/images/products/embroidered_anarkali_suit.png',
          description: 'Elegant anarkali suit with fine embroidery work.',
          isFeatured: true,
        ),
        Product(
          id: 'p008',
          name: 'Casual Tunic Top',
          category: 'Women Fashion',
          price: 249,
          originalPrice: 599,
          discount: 58,
          rating: 3.9,
          reviewCount: 211,
          imageUrl: 'assets/images/products/casual_tunic_top.png',
          description: 'Breezy tunic top for casual outings.',
          isBestSeller: true,
        ),
        Product(
          id: 'p008b',
          name: 'Maxi Dress Floral',
          category: 'Women Fashion',
          price: 599,
          originalPrice: 1299,
          discount: 54,
          rating: 4.2,
          reviewCount: 432,
          imageUrl: 'assets/images/products/maxi_dress_floral.png',
          description: 'Breezy floral maxi dress for summer outings.',
          isNewArrival: true,
          isPopular: true,
        ),
        Product(
          id: 'p008c',
          name: 'Salwar Kameez Set',
          category: 'Women Fashion',
          price: 749,
          originalPrice: 1599,
          discount: 53,
          rating: 4.3,
          reviewCount: 567,
          imageUrl: 'assets/images/products/salwar_kameez_set.png',
          description: 'Traditional salwar kameez with dupatta for festive occasions.',
          isBestSeller: true,
        ),

        // â”€â”€ Men Fashion â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        Product(
          id: 'p009',
          name: "Men Casual T-Shirt",
          category: 'Men Fashion',
          price: 249,
          originalPrice: 499,
          discount: 50,
          rating: 4.1,
          reviewCount: 1543,
          imageUrl: 'assets/images/products/men_casual_t-shirt.png',
          description: 'Comfortable cotton t-shirt for everyday wear.',
          isPopular: true,
          isBestSeller: true,
        ),
        Product(
          id: 'p010',
          name: 'Classic Straight Jeans',
          category: 'Men Fashion',
          price: 599,
          originalPrice: 1299,
          discount: 54,
          rating: 4.3,
          reviewCount: 876,
          imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400',
          description: 'Classic straight fit jeans for a timeless look.',
          isFeatured: true,
        ),
        Product(
          id: 'p011',
          name: 'Men Formal Shirt',
          category: 'Men Fashion',
          price: 449,
          originalPrice: 899,
          discount: 50,
          rating: 4.2,
          reviewCount: 543,
          imageUrl: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=400',
          description: 'Crisp formal shirt perfect for office wear.',
          isNewArrival: true,
        ),
        Product(
          id: 'p012',
          name: 'Men Ethnic Kurta',
          category: 'Men Fashion',
          price: 399,
          originalPrice: 799,
          discount: 50,
          rating: 4.0,
          reviewCount: 321,
          imageUrl: 'assets/images/products/men_ethnic_kurta.png',
          description: 'Traditional kurta for festivals and occasions.',
          isPopular: true,
        ),
        Product(
          id: 'p012b',
          name: 'Cotton Kurta Pajama Set',
          category: 'Men Fashion',
          price: 549,
          originalPrice: 1199,
          discount: 54,
          rating: 4.3,
          reviewCount: 543,
          imageUrl: 'assets/images/products/cotton_kurta_pajama_set.png',
          description: 'Premium cotton kurta pajama for festivals.',
          isBestSeller: true,
        ),
        Product(
          id: 'p012c',
          name: 'Men Polo T-Shirt',
          category: 'Men Fashion',
          price: 349,
          originalPrice: 799,
          discount: 56,
          rating: 4.2,
          reviewCount: 765,
          imageUrl: 'assets/images/products/men_polo_t-shirt.png',
          description: 'Classic polo t-shirt for smart casual look.',
          isPopular: true,
          isFeatured: true,
        ),
        Product(
          id: 'p012d',
          name: 'Men baggy jeans',
          category: 'Men Fashion',
          price: 499,
          originalPrice: 1099,
          discount: 55,
          rating: 4.1,
          reviewCount: 432,
          imageUrl: 'assets/images/products/men_baggy_jeans.png',
          description: 'baggy jeans for smart casual occasions.',
          isNewArrival: true,
        ),

        // â”€â”€ Kids â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        Product(
          id: 'p013',
          name: 'Kids girl Party Dress',
          category: 'Kids',
          price: 449,
          originalPrice: 899,
          discount: 50,
          rating: 4.5,
          reviewCount: 234,
          imageUrl: 'assets/images/products/kids_girl_party_dress.png',
          description: 'Adorable party dress for little girls.',
          isFeatured: true,
          isNewArrival: true,
        ),
        Product(
          id: 'p014',
          name: "Boys Denim Set",
          category: 'Kids',
          price: 349,
          originalPrice: 699,
          discount: 50,
          rating: 4.2,
          reviewCount: 187,
          imageUrl: 'assets/images/products/boys_denim_set.png',
          description: 'Trendy denim set for boys. Comfortable and stylish.',
          isPopular: true,
        ),
        Product(
          id: 'p015',
          name: 'Kids Winter Jacket',
          category: 'Kids',
          price: 699,
          originalPrice: 1499,
          discount: 53,
          rating: 4.3,
          reviewCount: 156,
          imageUrl: 'assets/images/products/kids_winter_jacket.png',
          description: 'Warm and cozy winter jacket for kids.',
          isBestSeller: true,
        ),
        Product(
          id: 'p015b',
          name: 'Girls Frock Set',
          category: 'Kids',
          price: 299,
          originalPrice: 699,
          discount: 57,
          rating: 4.4,
          reviewCount: 298,
          imageUrl: 'assets/images/products/girls_frock_set.png',
          description: 'Cute frock set for girls aged 3-8 years.',
          isPopular: true,
          isFeatured: true,
        ),
        Product(
          id: 'p015c',
          name: 'Kids School Bag',
          category: 'Kids',
          price: 499,
          originalPrice: 999,
          discount: 50,
          rating: 4.3,
          reviewCount: 421,
          imageUrl: 'assets/images/products/kids_school_bag.png',
          description: 'Durable and spacious school bag with multiple pockets.',
          isBestSeller: true,
        ),

        // â”€â”€ Beauty â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        Product(
          id: 'p016',
          name: 'Lipstick Set of 6',
          category: 'Beauty',
          price: 299,
          originalPrice: 699,
          discount: 57,
          rating: 4.4,
          reviewCount: 2345,
          imageUrl: 'assets/images/products/lipstick_set_of_6.png',
          description: 'Long-lasting matte lipstick set in 6 shades.',
          isFeatured: true,
          isPopular: true,
        ),
        Product(
          id: 'p017',
          name: 'Foundation with SPF',
          category: 'Beauty',
          price: 399,
          originalPrice: 799,
          discount: 50,
          rating: 4.1,
          reviewCount: 876,
          imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400',
          description: 'Lightweight foundation with SPF 30 protection.',
          isNewArrival: true,
        ),
        Product(
          id: 'p018',
          name: 'Eyeshadow Palette',
          category: 'Beauty',
          price: 499,
          originalPrice: 999,
          discount: 50,
          rating: 4.3,
          reviewCount: 543,
          imageUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400',
          description: '12-shade eyeshadow palette with matte and shimmer.',
          isBestSeller: true,
        ),
        Product(
          id: 'p018b',
          name: 'Blush & Bronzer Duo',
          category: 'Beauty',
          price: 349,
          originalPrice: 799,
          discount: 56,
          rating: 4.2,
          reviewCount: 654,
          imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400',
          description: 'Buildable blush and bronzer duo for natural glow.',
          isPopular: true,
          isNewArrival: true,
        ),

        // â”€â”€ Jewellery â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        Product(
          id: 'p019',
          name: 'Gold Plated Necklace Set',
          category: 'Jewellery',
          price: 499,
          originalPrice: 999,
          discount: 50,
          rating: 4.2,
          reviewCount: 654,
          imageUrl: 'assets/images/products/gold_plated_necklace_set.png',
          description: 'Elegant gold plated necklace set with earrings.',
          isFeatured: true,
        ),
        Product(
          id: 'p020',
          name: 'Pearl Earrings',
          category: 'Jewellery',
          price: 199,
          originalPrice: 499,
          discount: 60,
          rating: 4.4,
          reviewCount: 432,
          imageUrl: 'assets/images/products/pearl_earrings.png',
          description: 'Classic pearl stud earrings for everyday elegance.',
          isPopular: true,
          isBestSeller: true,
        ),
        Product(
          id: 'p021',
          name: 'Kundan Bangles Set',
          category: 'Jewellery',
          price: 349,
          originalPrice: 799,
          discount: 56,
          rating: 4.1,
          reviewCount: 321,
          imageUrl: 'assets/images/products/kundan_bangles_set.png',
          description: 'Traditional kundan bangles set of 12 pieces.',
          isNewArrival: true,
        ),
        Product(
          id: 'p021b',
          name: 'Oxidized Silver Ring',
          category: 'Jewellery',
          price: 149,
          originalPrice: 349,
          discount: 57,
          rating: 4.3,
          reviewCount: 543,
          imageUrl: 'assets/images/products/oxidized_silver_ring.png',
          description: 'Handcrafted oxidized silver ring with tribal design.',
          isPopular: true,
          isFeatured: true,
        ),
        Product(
          id: 'p021c',
          name: 'Maang Tikka',
          category: 'Jewellery',
          price: 249,
          originalPrice: 599,
          discount: 58,
          rating: 4.5,
          reviewCount: 765,
          imageUrl: 'assets/images/products/maang_tikka.png',
          description: 'Elegant maang tikka for bridal and festive occasions.',
          isBestSeller: true,
        ),

        // â”€â”€ Electronics â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        Product(
          id: 'p022',
          name: 'Bluetooth Earbuds',
          category: 'Electronics',
          price: 999,
          originalPrice: 2499,
          discount: 60,
          rating: 4.3,
          reviewCount: 3456,
          imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400',
          description: 'True wireless earbuds with noise cancellation.',
          isFeatured: true,
          isPopular: true,
          isBestSeller: true,
        ),
        Product(
          id: 'p023',
          name: 'Smart Watch',
          category: 'Electronics',
          price: 1499,
          originalPrice: 3999,
          discount: 62,
          rating: 4.2,
          reviewCount: 1234,
          imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
          description: 'Smart watch with health tracking and notifications.',
          isFeatured: true,
        ),
        Product(
          id: 'p024',
          name: 'Power Bank',
          category: 'Electronics',
          price: 799,
          originalPrice: 1999,
          discount: 60,
          rating: 4.4,
          reviewCount: 987,
          imageUrl: 'assets/images/products/power_bank.png',
          description: 'Fast charging power bank with 20000mAh capacity.',
          isNewArrival: true,
        ),
        Product(
          id: 'p025',
          name: 'Phone Stand & Holder',
          category: 'Electronics',
          price: 199,
          originalPrice: 499,
          discount: 60,
          rating: 4.0,
          reviewCount: 654,
          imageUrl: 'assets/images/products/phone_stand_&_holder.png',
          description: 'Adjustable phone stand for desk and bedside.',
          isPopular: true,
        ),
        Product(
          id: 'p025b',
          name: 'Wireless Keyboard',
          category: 'Electronics',
          price: 799,
          originalPrice: 1799,
          discount: 56,
          rating: 4.1,
          reviewCount: 321,
          imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400',
          description: 'Slim wireless keyboard with 6-month battery life.',
          isNewArrival: true,
        ),
        Product(
          id: 'p025c',
          name: 'Bluetooth Speaker',
          category: 'Electronics',
          price: 1299,
          originalPrice: 2999,
          discount: 57,
          rating: 4.5,
          reviewCount: 2134,
          imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400',
          description: 'Portable waterproof Bluetooth speaker with 12hr battery.',
          isFeatured: true,
          isBestSeller: true,
        ),
        Product(
          id: 'p025d',
          name: 'USB-C Fast Charger',
          category: 'Electronics',
          price: 349,
          originalPrice: 799,
          discount: 56,
          rating: 4.3,
          reviewCount: 876,
          imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400',
          description: '65W GaN fast charger with USB-C and USB-A ports.',
          isPopular: true,
        ),

        // â”€â”€ Home & Kitchen â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        Product(
          id: 'p026',
          name: 'Non-Stick Cookware Set',
          category: 'Home & Kitchen',
          price: 1299,
          originalPrice: 2999,
          discount: 57,
          rating: 4.5,
          reviewCount: 876,
          imageUrl: 'assets/images/products/non-stick_cookware_set.png',
          description: '5-piece non-stick cookware set for modern kitchen.',
          isFeatured: true,
          isBestSeller: true,
        ),
        Product(
          id: 'p027',
          name: 'Printed Bed Sheet Set',
          category: 'Home & Kitchen',
          price: 499,
          originalPrice: 999,
          discount: 50,
          rating: 4.2,
          reviewCount: 543,
          imageUrl: 'assets/images/products/printed_bed_sheet_set.png',
          description: 'Double bed sheet with 2 pillow covers. 100% cotton.',
          isPopular: true,
        ),
        Product(
          id: 'p028',
          name: 'Wall Clock Wooden',
          category: 'Home & Kitchen',
          price: 349,
          originalPrice: 799,
          discount: 56,
          rating: 4.3,
          reviewCount: 321,
          imageUrl: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400',
          description: 'Elegant wooden wall clock for modern homes.',
          isNewArrival: true,
        ),
        Product(
          id: 'p029',
          name: 'Kitchen Organizer Set',
          category: 'Home & Kitchen',
          price: 599,
          originalPrice: 1299,
          discount: 54,
          rating: 4.1,
          reviewCount: 234,
          imageUrl: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400',
          description: 'Complete kitchen organizer set for neat storage.',
          isBestSeller: true,
        ),
        Product(
          id: 'p029b',
          name: 'Stainless Steel Lunch Box',
          category: 'Home & Kitchen',
          price: 299,
          originalPrice: 699,
          discount: 57,
          rating: 4.4,
          reviewCount: 987,
          imageUrl: 'assets/images/products/stainless_steel_lunch_box.png',
          description: '3-tier stainless steel lunch box, leak-proof.',
          isPopular: true,
          isFeatured: true,
        ),
        Product(
          id: 'p029c',
          name: 'Decorative Cushion Set',
          category: 'Home & Kitchen',
          price: 449,
          originalPrice: 999,
          discount: 55,
          rating: 4.2,
          reviewCount: 432,
          imageUrl: 'assets/images/products/decorative_cushion_set.png',
          description: 'Set of 5 decorative cushion covers for sofa.',
          isNewArrival: true,
        ),

        // â”€â”€ Bags â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        Product(
          id: 'p030',
          name: 'Women Handbag',
          category: 'Bags',
          price: 699,
          originalPrice: 1499,
          discount: 53,
          rating: 4.3,
          reviewCount: 765,
          imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400',
          description: 'Stylish PU leather handbag with multiple compartments.',
          isFeatured: true,
          isPopular: true,
        ),
        Product(
          id: 'p031',
          name: 'men Laptop Bag',
          category: 'Bags',
          price: 899,
          originalPrice: 1999,
          discount: 55,
          rating: 4.4,
          reviewCount: 543,
          imageUrl: 'assets/images/products/men_laptop_bag.png',
          description: 'Waterproof laptop backpack.',
          isBestSeller: true,
        ),
        Product(
          id: 'p032',
          name: 'Sling Bag',
          category: 'Bags',
          price: 349,
          originalPrice: 799,
          discount: 56,
          rating: 4.0,
          reviewCount: 321,
          imageUrl: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=400',
          description: 'Compact sling bag for daily essentials.',
          isNewArrival: true,
        ),
        Product(
          id: 'p032b',
          name: 'Tote Bag Canvas',
          category: 'Bags',
          price: 249,
          originalPrice: 599,
          discount: 58,
          rating: 4.2,
          reviewCount: 654,
          imageUrl: 'assets/images/products/tote_bag_canvas.png',
          description: 'Eco-friendly canvas tote bag for shopping and travel.',
          isPopular: true,
          isFeatured: true,
        ),

        // â”€â”€ Accessories â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        Product(
          id: 'p033',
          name: 'Sunglasses Polarized',
          category: 'Accessories',
          price: 299,
          originalPrice: 699,
          discount: 57,
          rating: 4.2,
          reviewCount: 876,
          imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400',
          description: 'UV400 polarized sunglasses for summer.',
          isFeatured: true,
          isPopular: true,
        ),
        Product(
          id: 'p034',
          name: 'Hair Accessories Kit',
          category: 'Accessories',
          price: 149,
          originalPrice: 399,
          discount: 63,
          rating: 4.1,
          reviewCount: 543,
          imageUrl: 'assets/images/products/hair_accessories_kit.png',
          description: 'Complete hair accessories kit with clips and bands.',
          isBestSeller: true,
        ),
        Product(
          id: 'p035',
          name: 'Scarf & Stole',
          category: 'Accessories',
          price: 199,
          originalPrice: 499,
          discount: 60,
          rating: 4.0,
          reviewCount: 234,
          imageUrl: 'assets/images/products/scarf_&_stole.png',
          description: 'Lightweight scarf in multiple colors.',
          isNewArrival: true,
        ),
        Product(
          id: 'p035b',
          name: 'Sports Water Bottle',
          category: 'Accessories',
          price: 199,
          originalPrice: 499,
          discount: 60,
          rating: 4.3,
          reviewCount: 654,
          imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400',
          description: 'BPA-free stainless steel water bottle 1L.',
          isPopular: true,
        ),
        Product(
          id: 'p035c',
          name: 'Yoga Mat',
          category: 'Accessories',
          price: 399,
          originalPrice: 899,
          discount: 56,
          rating: 4.4,
          reviewCount: 432,
          imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400',
          description: 'Anti-slip yoga mat with carrying strap.',
          isFeatured: true,
        ),
        Product(
          id: 'p035d',
          name: 'Leather Belt Men',
          category: 'Accessories',
          price: 299,
          originalPrice: 699,
          discount: 57,
          rating: 4.2,
          reviewCount: 543,
          imageUrl: 'assets/images/products/leather_belt_men.png',
          description: 'Genuine leather belt with metal buckle for men.',
          isBestSeller: true,
        ),

        // â”€â”€ Footwear â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        Product(
          id: 'p036',
          name: 'Women Heels',
          category: 'Footwear',
          price: 599,
          originalPrice: 1299,
          discount: 54,
          rating: 4.2,
          reviewCount: 654,
          imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400',
          description: 'Elegant block heels for formal and casual wear.',
          isFeatured: true,
        ),
        Product(
          id: 'p037',
          name: 'Men Casual Sneakers',
          category: 'Footwear',
          price: 799,
          originalPrice: 1799,
          discount: 56,
          rating: 4.3,
          reviewCount: 987,
          imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
          description: 'Lightweight sneakers for everyday comfort.',
          isPopular: true,
          isBestSeller: true,
        ),
        Product(
          id: 'p038',
          name: 'Kids Canvas Shoes',
          category: 'Footwear',
          price: 399,
          originalPrice: 799,
          discount: 50,
          rating: 4.1,
          reviewCount: 321,
          imageUrl: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400',
          description: 'Durable canvas shoes for school and play.',
          isNewArrival: true,
        ),
        Product(
          id: 'p038b',
          name: 'Women Flats',
          category: 'Footwear',
          price: 449,
          originalPrice: 999,
          discount: 55,
          rating: 4.3,
          reviewCount: 765,
          imageUrl: 'https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?w=400',
          description: 'Comfortable leather flats for all-day wear.',
          isPopular: true,
          isFeatured: true,
        ),
        Product(
          id: 'p038c',
          name: 'Men Formal Shoes',
          category: 'Footwear',
          price: 999,
          originalPrice: 2299,
          discount: 57,
          rating: 4.4,
          reviewCount: 432,
          imageUrl: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400',
          description: 'Classic Oxford formal shoes for office and events.',
          isBestSeller: true,
        ),

        // â”€â”€ Skincare â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        Product(
          id: 'p039',
          name: 'Vitamin C Serum',
          category: 'Skincare',
          price: 349,
          originalPrice: 799,
          discount: 56,
          rating: 4.5,
          reviewCount: 2345,
          imageUrl: 'assets/images/products/vitamin_c_serum.png',
          description: 'Brightening vitamin C serum for glowing skin.',
          isFeatured: true,
          isPopular: true,
        ),
        Product(
          id: 'p040',
          name: 'Face Wash Gel',
          category: 'Skincare',
          price: 149,
          originalPrice: 299,
          discount: 50,
          rating: 4.2,
          reviewCount: 1234,
          imageUrl: 'assets/images/products/Face_Wash_Gel.png',
          description: 'Deep cleansing face wash for all skin types.',
          isBestSeller: true,
        ),
        Product(
          id: 'p041',
          name: 'Moisturizer SPF 50',
          category: 'Skincare',
          price: 299,
          originalPrice: 599,
          discount: 50,
          rating: 4.3,
          reviewCount: 876,
          imageUrl: 'assets/images/products/moisturizer_spf_50.png',
          description: 'Daily moisturizer with SPF 50 sun protection.',
          isNewArrival: true,
        ),
        Product(
          id: 'p042',
          name: 'Under Eye Cream',
          category: 'Skincare',
          price: 199,
          originalPrice: 499,
          discount: 60,
          rating: 4.0,
          reviewCount: 543,
          imageUrl: 'assets/images/products/Under_Eye_Cream.png',
          description: 'Anti-dark circle under eye cream.',
          isPopular: true,
        ),
        Product(
          id: 'p042b',
          name: 'sunscreen spf 50',
          category: 'Skincare',
          price: 249,
          originalPrice: 599,
          discount: 58,
          rating: 4.4,
          reviewCount: 1876,
          imageUrl: 'assets/images/products/sunscreen_spf_50.png',
          description: 'Broad spectrum SPF 50 sunscreen, water resistant.',
          isFeatured: true,
          isBestSeller: true,
        ),

        // â”€â”€ Makeup â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
        Product(
          id: 'p043',
          name: 'Kajal Black',
          category: 'Makeup',
          price: 99,
          originalPrice: 199,
          discount: 50,
          rating: 4.4,
          reviewCount: 3456,
          imageUrl: 'assets/images/products/kajal_black.png',
          description: 'Smudge-proof kajal for bold eyes.',
          isFeatured: true,
          isBestSeller: true,
        ),
        Product(
          id: 'p044',
          name: 'Compact Powder',
          category: 'Makeup',
          price: 199,
          originalPrice: 449,
          discount: 56,
          rating: 4.2,
          reviewCount: 1234,
          imageUrl: 'assets/images/products/compact_powder.png',
          description: 'Long-lasting compact powder for matte finish.',
          isPopular: true,
        ),
        Product(
          id: 'p045',
          name: 'Lip Gloss Set',
          category: 'Makeup',
          price: 249,
          originalPrice: 599,
          discount: 58,
          rating: 4.1,
          reviewCount: 876,
          imageUrl: 'assets/images/products/lip_gloss_set.png',
          description: 'Glossy lip gloss set in 5 shades.',
          isNewArrival: true,
        ),
        Product(
          id: 'p045b',
          name: 'Mascara Volumizing',
          category: 'Makeup',
          price: 199,
          originalPrice: 449,
          discount: 56,
          rating: 4.3,
          reviewCount: 987,
          imageUrl: 'assets/images/products/mascara_volumizing.png',
          description: 'Volumizing and lengthening mascara for dramatic lashes.',
          isPopular: true,
          isFeatured: true,
        ),
        Product(
          id: 'p045c',
          name: 'BB Cream Tinted',
          category: 'Makeup',
          price: 299,
          originalPrice: 699,
          discount: 57,
          rating: 4.2,
          reviewCount: 654,
          imageUrl: 'assets/images/products/BB_cream_tinted.png',
          description: 'Multi-function BB cream with SPF and coverage.',
          isBestSeller: true,
        ),
      ];

  static List<Product> getByCategory(String category) {
    if (category == 'All Categories') return products;
    return products
        .where((p) => p.category.toLowerCase() == category.toLowerCase())
        .toList();
  }
}
